In [1]:
import cv2 as cv2
import numpy as np
import matplotlib.pyplot as plt
import os

# Chpater 01

## BGR, Blue - 0, Green - 1, Red - 2

In [2]:
#open cv
#Reading and writing files
#Chapter 01
img = np.zeros((3,3), dtype = np.uint8)#uint8 = unsigned integer (0 to 255)
print(img)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


#### Converting to RGB

In [3]:
#converting to RGB
img1 = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
print(img1)#Consist with 3 layers

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


#### Image Structure

In [4]:
#structure of in image
i1shape=img.shape
i2shape=img1.shape
print(f'This is 2D Array image, shape is: {i1shape}')
print(f'This is 3D Array image, shape is: {i2shape}')

This is 2D Array image, shape is: (3, 3)
This is 3D Array image, shape is: (3, 3, 3)


#### Image Loading ans saving

In [6]:
#image loading
image1 = cv2.imread("C:\\Lachin\\Data Science\\Data science\\Opencv\\image1.jpg")#By default RGB color image is shown
cv2.imwrite("C:\Lachin\Data Science\Data science\Opencv\mypic.png", image1)#JPG is now turned to PNG
#plt.imshow(image1)#Show an image using matplotlib

True

#### Converting RGB to Grayscale

In [20]:
img_gray = cv2.cvtColor(image1, cv2.COLOR_RGB2GRAY)#Convert in to GrayScale
img_gray.shape
#lt.imshow(img_gray)

(636, 1024)

#### Directly read as grayscale

In [22]:
#Load PNG as Grayscale image
gray_image = cv2.imread("C:\Lachin\Data Science\Data science\Opencv\mypic.png", cv2.IMREAD_GRAYSCALE)#Open as grayscale img
cv2.imwrite("C:\Lachin\Data Science\Data science\Opencv\Mypic_Gray.png", gray_image)#Saved as Grayscale image

True

#### Accessing Image elements

In [23]:
print(gray_image.shape)

(636, 1024)


In [37]:
#GrayScale
print(gray_image.item((0,0)))#pixel of the top left corner
print(gray_image.item((125,85)))

#RGB
print(image1.shape)
print(image1.item((10,25,1)))


41
21
(636, 1024, 3)
70


In [41]:
for i in range(3):
    print("Byte values of a certain image with respective channel: {}".format(image1.item((25,45,i))))

Byte values of a certain image with respective channel: 68
Byte values of a certain image with respective channel: 92
Byte values of a certain image with respective channel: 112


### Converting image between raw bytes

In [47]:
#creating random bytearrays
randombytearray = bytearray(os.urandom(120000))
flatnumpyarray = np.array(randombytearray)
grayimage = flatnumpyarray.reshape(400,300)#grayscale image
path = "C:\\Lachin\\Data Science\\Data science\\Opencv\\"
cv2.imwrite(path + "Gray.png", grayimage)
rgbimage = flatnumpyarray.reshape(100,400,3)
cv2.imwrite(path+"rgbimage.png", rgbimage)

True

#### Accessing images with numpy arrays

In [4]:
path = 'C:\\Lachin\\Data Science\\Data science\\Opencv\\'

In [15]:
image = cv2.imread(path + 'mypic.png')#Load the image
image [0,0] = [255,255,255]#top left corner pixel will be white
cv2.imwrite(path+'White_dot_pic.png', image)

True

In [29]:
image.shape

(636, 1024, 3)

In [23]:
list1 = ['red','green','blue']
for i , j in zip(list1, range(3)):
    print(f'this the pixel value of respective {i} color channel')
    print(image.item(45,25,j))

this the pixel value of respective red color channel
45
this the pixel value of respective green color channel
54
this the pixel value of respective blue color channel
68


In [28]:
image.itemset((45,25,0),255)#Set the respective pixel to the 255
image.itemset((45,25,1),75)#set the respective pixel to the 75
image.itemset((45,25,2),98)#Set the respective pixel to the 98
list1 = ['red','green','blue']
for i , j in zip(list1, range(3)):
    print(f'this the pixel value of respective {i} color channel')
    print(image.item(45,25,j))

this the pixel value of respective red color channel
255
this the pixel value of respective green color channel
75
this the pixel value of respective blue color channel
98


In [35]:
image[:,:,1] = 0 #All the green channels pixels are green now
image[:,:,0] = 0 #All the Blues are gone 
#Indexing is far better suitable, rather than loops, it takes times
cv2.imwrite(path+'White_dot_pic02.png', image)#now all the green is gone

True

#### Region of interest

In [38]:
#How read in an image
cv2.imshow('my_image', image)
cv2.waitKey()
cv2.destroyAllWindows()

In [41]:
my_roi = image[0:100,0:100]
my_roi1 = image[300:400,300:400]

In [42]:
#some properties of numpy arrays
print(image.shape)
print(image.size)#pixels
print(image.dtype)

(636, 1024, 3)
1953792
uint8


#### Displaying camera frames in windows

In [4]:
clicked = False

def onmouse(event,x,y,flags,param):
    global clicked #Can access in any environment
    if event == cv2.EVENT_LBUTTONUP:
        clicked = True
    print('function')
    
camera_capture = cv2.VideoCapture(0)
cv2.namedWindow('MyWindow')
cv2.setMouseCallback('MyWindow', onmouse)
print('Showing Camera feed. Click window or press ant key to stop')
success,frame = camera_capture.read()
while success  and (cv2.waitKey(1) == -1) and (not clicked):
    cv2.imshow('MyWindow', frame)
    success,frame = camera_capture.read()
    print('Loop')
cv2.destroyWindow('MyWindow')
camera_capture.release()
    

Showing Camera feed. Click window or press ant key to stop
function
function
Loop
Loop
Loop
Loop
Loop
Loop
Loop
Loop
Loop
Loop
Loop
Loop
Loop
Loop
Loop
Loop
Loop
Loop
Loop
Loop
Loop
Loop
Loop
Loop
Loop
Loop
Loop
Loop
Loop
Loop
Loop
function
Loop
Loop
function
