In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import cv2 as cv2

In [2]:
path = 'C:\\Lachin\\Data Science\\Data science\\Opencv\\'

In [3]:
image = cv2.imread(path+'image1.jpg')

#### Image Reading

In [4]:
cv2.imshow('image', image)
cv2.waitKey()
cv2.destroyAllWindows()

#### Image Converting

In [5]:
imag_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow('Gray Image', imag_gray)
cv2.waitKey()
cv2.destroyAllWindows()

#### Image element accessing and changing

In [6]:
image.shape

(636, 1024, 3)

In [7]:
image.item((356,1021,2))

36

In [8]:
image.itemset((356,1021,2),255)

#### Different color channels

In [9]:
B, G, R = cv2.split(image)
cv2.imshow('Orginal Image', image)
cv2.imshow('Blue Image', B)
cv2.imshow('Green Image', G)
cv2.imshow('Red Image',R)
cv2.waitKey()
cv2.destroyAllWindows()


#### Image Merging

In [10]:
merge = cv2.merge([B+50,G+100,R+100])
cv2.imshow('merge Image', merge)
cv2.waitKey()
cv2.destroyAllWindows()

#### Image capturing through webcam

In [19]:
path1 = 'C:\\Lachin\\Data Science\\Data science\\Opencv\\my Images\\'
img = cv2.VideoCapture(0)
count=0

while (True):
    count+=1
    check, frame = img.read()
    cv2.imshow("my frame", frame)
    if cv2.waitKey(1000) ==ord("q"):#waitkey is waiting for a key board argument
        break
    print(frame.shape)
    cv2.imwrite(path1+f'img{count}.jpg', frame)
img.release()
cv2.destroyAllWindows()
    

(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)


#### Video Capturing through webcam

In [32]:
image = cv2.VideoCapture(0)
fourcc_code = cv2.VideoWriter_fourcc(*"WMV3")
video = cv2.VideoWriter(path1+'my_video.wmv',fourcc_code,10.0,(480,640))

while (True):
    check, frame = image.read()
    video.write(frame)
    cv2.imshow('my_image', frame)
    if cv2.waitKey(1) == ord('q'):
        break
    print(frame.shape)
    cv2.imwrite(path1+'my_image.jpg', frame)
video.release()
image.release()
cv2.destroyAllWindows()

(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 

#### Draw Geometric Shapes

In [2]:
path = 'C:\\Lachin\\Data Science\\Data science\\Opencv\\'

In [3]:
image = cv2.imread(path+'image1.jpg')

In [4]:
image.shape

(636, 1024, 3)

In [5]:
image.size

1953792

In [21]:
636*1024*3

1953792

In [24]:
image.item((635,1023,0))

0

In [8]:
cv2.imshow('My_image', image)
cv2.waitKey()
cv2.destroyAllWindows()

In [44]:
#Drawing Line
cv2.line(image,(0,318),(1000,318),(0,0,255),2)
#pt are given as (x_coordinates,y_coordinates)

array([[[ 25,  98,  75],
        [ 25,  98,  75],
        [  0,   0, 255],
        ...,
        [199, 221, 233],
        [200, 222, 234],
        [200, 222, 234]],

       [[ 25,  98,  75],
        [ 25,  98,  75],
        [ 25,  98,  75],
        ...,
        [197, 219, 231],
        [197, 219, 231],
        [197, 219, 231]],

       [[ 25,  98,  75],
        [ 25,  98,  75],
        [ 25,  98,  75],
        ...,
        [194, 216, 228],
        [194, 216, 228],
        [194, 216, 228]],

       ...,

       [[  0,   0, 255],
        [  0,   0, 255],
        [ 77,  63,  64],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [123,  97,  91]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [ 78,  68,  68],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [ 81,  76,  75],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]]

In [27]:
#Draw Arrow
cv2.arrowedLine(image,(0,0),(452,965),(25,98,75),2)

array([[[ 25,  98,  75],
        [ 25,  98,  75],
        [  0,   0, 255],
        ...,
        [199, 221, 233],
        [200, 222, 234],
        [200, 222, 234]],

       [[ 25,  98,  75],
        [ 25,  98,  75],
        [ 25,  98,  75],
        ...,
        [197, 219, 231],
        [197, 219, 231],
        [197, 219, 231]],

       [[ 25,  98,  75],
        [ 25,  98,  75],
        [ 25,  98,  75],
        ...,
        [194, 216, 228],
        [194, 216, 228],
        [194, 216, 228]],

       ...,

       [[ 79,  65,  66],
        [ 77,  63,  64],
        [ 77,  63,  64],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [123,  97,  91]],

       [[ 82,  72,  72],
        [ 81,  71,  71],
        [ 78,  68,  68],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[ 83,  78,  77],
        [ 84,  79,  78],
        [ 81,  76,  75],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]]

In [28]:
#Draw Rectangle
cv2.rectangle(image,(25,63),(100,100),(145,98,63),1)

array([[[ 25,  98,  75],
        [ 25,  98,  75],
        [  0,   0, 255],
        ...,
        [199, 221, 233],
        [200, 222, 234],
        [200, 222, 234]],

       [[ 25,  98,  75],
        [ 25,  98,  75],
        [ 25,  98,  75],
        ...,
        [197, 219, 231],
        [197, 219, 231],
        [197, 219, 231]],

       [[ 25,  98,  75],
        [ 25,  98,  75],
        [ 25,  98,  75],
        ...,
        [194, 216, 228],
        [194, 216, 228],
        [194, 216, 228]],

       ...,

       [[ 79,  65,  66],
        [ 77,  63,  64],
        [ 77,  63,  64],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [123,  97,  91]],

       [[ 82,  72,  72],
        [ 81,  71,  71],
        [ 78,  68,  68],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[ 83,  78,  77],
        [ 84,  79,  78],
        [ 81,  76,  75],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]]

In [42]:
#Draw Circle
cv2.circle(image,(512,318),200,(0,25,69))

array([[[ 25,  98,  75],
        [ 25,  98,  75],
        [  0,   0, 255],
        ...,
        [199, 221, 233],
        [200, 222, 234],
        [200, 222, 234]],

       [[ 25,  98,  75],
        [ 25,  98,  75],
        [ 25,  98,  75],
        ...,
        [197, 219, 231],
        [197, 219, 231],
        [197, 219, 231]],

       [[ 25,  98,  75],
        [ 25,  98,  75],
        [ 25,  98,  75],
        ...,
        [194, 216, 228],
        [194, 216, 228],
        [194, 216, 228]],

       ...,

       [[  0,   0, 255],
        [  0,   0, 255],
        [ 77,  63,  64],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [123,  97,  91]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [ 78,  68,  68],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [ 81,  76,  75],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]]

In [7]:
#Put a text
cv2.putText(image,"Image",(65,45),cv2.FONT_HERSHEY_PLAIN,0.6,(255,255,255),2)

array([[[ 26,  39,  53],
        [ 15,  26,  40],
        [  4,  13,  27],
        ...,
        [199, 221, 233],
        [200, 222, 234],
        [200, 222, 234]],

       [[ 27,  38,  52],
        [ 16,  27,  41],
        [  8,  17,  31],
        ...,
        [197, 219, 231],
        [197, 219, 231],
        [197, 219, 231]],

       [[ 25,  37,  49],
        [ 20,  29,  43],
        [ 15,  24,  38],
        ...,
        [194, 216, 228],
        [194, 216, 228],
        [194, 216, 228]],

       ...,

       [[ 79,  65,  66],
        [ 77,  63,  64],
        [ 77,  63,  64],
        ...,
        [123, 102, 100],
        [121,  96,  92],
        [123,  97,  91]],

       [[ 82,  72,  72],
        [ 81,  71,  71],
        [ 78,  68,  68],
        ...,
        [124, 103, 101],
        [126, 101,  97],
        [134, 108, 102]],

       [[ 83,  78,  77],
        [ 84,  79,  78],
        [ 81,  76,  75],
        ...,
        [123, 100,  98],
        [124,  99,  95],
        [133, 107, 101]]

#### Mouse Event Handling

##### Putting text with mouse click

In [12]:
def onmouse(event, x, y, flags, param):
    if (event == cv2.EVENT_LBUTTONUP):
        cv2.putText(image,"Image",(x,y),cv2.FONT_HERSHEY_PLAIN,2,(255,255,255),2)
    if (event == cv2.EVENT_LBUTTONDBLCLK):
        cv2.imwrite('C:\\Lachin\\Data Science\\Data science\\Opencv\\mouse.jpg',image)
    cv2.imshow('frame', image)
        

In [13]:
image = cv2.imread(path+'image1.jpg')
cv2.imshow('frame', image)
cv2.setMouseCallback('frame', onmouse)
cv2.waitKey()
cv2.destroyAllWindows()
        

##### Drawing Shapes

In [26]:
def onmouse(event, x, y, flags, param):
    if (event == cv2.EVENT_LBUTTONUP):
        points.append((x,y))
        if(len(points)==2):
            cv2.line(image,points[0],points[1],(0,0,255),2)
    if (event == cv2.EVENT_MOUSEMOVE):
        points.append((x,y))
        if (len(points)>=2):
            cv2.line(image,points[-2],points[-1],(56,255,100),2)
    cv2.imshow('frame', image)
    
image = cv2.imread(path+'image1.jpg')
points=[]
cv2.imshow('frame', image)
cv2.setMouseCallback('frame', onmouse)
cv2.waitKey()
cv2.destroyAllWindows()
        


        

##### Calling for coordinates

In [15]:
def onmouse(event, x, y, flags, param):
    if (event == cv2.EVENT_LBUTTONUP):
        string1 = str(x)+","+str(y)
        cv2.putText(image,string1,(x,y),cv2.FONT_HERSHEY_PLAIN,2,(255,255,255),2)
    if (event == cv2.EVENT_LBUTTONDBLCLK):
        cv2.imwrite('C:\\Lachin\\Data Science\\Data science\\Opencv\\mouse.jpg',image)
    cv2.imshow('frame', image)

image = cv2.imread(path+'image1.jpg')
cv2.imshow('frame', image)
cv2.setMouseCallback('frame', onmouse)
cv2.waitKey()
cv2.destroyAllWindows()
        
        

##### Calling for color coordinates

In [29]:
def onmouse(event, x, y, flags, param):
    if (event == cv2.EVENT_RBUTTONUP):
        blue = str(image[y,x,0])
        green = str(image[y,x,1])
        red = str(image[y,x,2]) 
        cv2.putText(image,f"{blue},{green},{red}",(x,y),cv2.FONT_HERSHEY_PLAIN,2,(255,255,255),2)
    cv2.imshow('frame', image)
    
image = cv2.imread(path+'image1.jpg')
cv2.imshow('frame', image)
cv2.setMouseCallback('frame', onmouse)
cv2.waitKey()
cv2.destroyAllWindows()          

##### Color Picker

In [34]:
def onmouse(event, x, y, flags, param):
    if (event == cv2.EVENT_RBUTTONUP):
        blue = str(image[y,x,0])
        green = str(image[y,x,1])
        red = str(image[y,x,2]) 
        cv2.putText(image,f"{blue},{green},{red}",(x,y),cv2.FONT_HERSHEY_PLAIN,2,(255,255,255),2)
        image1 = np.zeros([512,512,3], np.uint8)
        image1[:] = [blue,green,red]
        cv2.imshow('frame1', image1)
    cv2.imshow('frame', image)
    
image = cv2.imread(path+'image1.jpg')
cv2.imshow('frame', image)
cv2.setMouseCallback('frame', onmouse)
cv2.waitKey()
cv2.destroyAllWindows()   

##### Cropping

In [57]:
def onmouse(event, x, y, flags, param):
    if (event == cv2.EVENT_LBUTTONUP):
        points.append((x,y))
        if(len(points)==2):
            cv2.rectangle(image,points[0],points[1],(0,0,255),2)
            print(points)
            image1 = image[points[0][1]:points[1][1],points[0][0]:points[1][0]]
            cv2.imshow('frame2', image1)
    cv2.imshow('frame', image)
    
image = cv2.imread(path+'image1.jpg')
points=[]
cv2.imshow('frame', image)
cv2.setMouseCallback('frame', onmouse)
cv2.waitKey()
cv2.destroyAllWindows()
        


[(371, 57), (1007, 618)]


#### Arithmetic Operations on Images

In [84]:
img1 = cv2.imread('C:\Lachin\Data Science\Data science\Opencv\image1.jpg')
img2 = cv2.imread('C:\Lachin\Data Science\Data science\Opencv\image2.jpg')
img5 = np.ones(img1.shape, np.uint8)
img5=img5*100


In [78]:
img3 = img1+100#All values are added by 100, if 255 exceeds, it will start again from 0

In [79]:
img4 =cv2.add(img1,100)#Only blue channel numbers are increased

In [80]:
img6 = cv2.add(img1,img5)#Increse the brightness of the picture
#if 255 is exceeded, it will not rewrite from the begining, it stops at 255

In [97]:
img2 = cv2.resize(img2, (img1.shape[1],img1.shape[0]))#resizing image 2 according to image 1
img7 = cv2.add(img1,img2)#Two images on top together

In [101]:
img8 = cv2.addWeighted(img2,0.7,img1,0.3,0)#Contro; the weights of the images

In [102]:
cv2.imshow('frame1', img1)
cv2.imshow('frame2', img2)
cv2.imshow('frame3', img8)
cv2.waitKey()
cv2.destroyAllWindows()

#### Bitwise Operations on Images

In [119]:
img1 = cv2.imread('C:\Lachin\Data Science\Data science\Opencv\image1.jpg')

In [120]:
im1 = np.zeros(img1.shape, np.uint8)
im2 = np.zeros(img1.shape, np.uint8)

In [127]:
cv2.rectangle(im1, (50,50),(300,300),(255,255,255),-1)
cv2.circle(im1, (275,275),25,(255,255,255),-1)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [128]:
im3 = cv2.bitwise_and(im1,im2)#Intersection area
im4 = cv2.bitwise_or(im1,im2)#Both area
im5 = cv2.bitwise_xor(im1,im2)
im6 = cv2.bitwise_not(im1,im2)

In [129]:
cv2.imshow('frame1', im1)
cv2.imshow('frame2', im2)
cv2.imshow('AND', im3)
cv2.imshow('OR', im4)
cv2.imshow('XOR', im5)
cv2.imshow('NOT', im6)
cv2.waitKey()
cv2.destroyAllWindows()

In [117]:
img1.shape

(636, 1024, 3)

### Image Processing

#### 1. Image Translation

In [17]:
image = cv2.imread('C:\Lachin\Data Science\Data science\Opencv\image1.jpg')

In [18]:
row, col, chan = image.shape

In [19]:
x=40
y=50

In [20]:
T = np.float64([[1,0,x],[0,1,y]])#This is the translation matrix which is used to translate the image

In [21]:
image2 = cv2.warpAffine(image, T, (row,col))#image will be transalte

In [25]:
cv2.imshow('Frame1', image)
cv2.imshow('frame2', image2)
cv2.waitKey()#Time waiting for a keyboard argument
cv2.destroyAllWindows()

##### Creating an animation

In [30]:
x=0
y=0

while(True):
    T = np.float64([[1,0,x],[0,1,y]])
    image2 = cv2.warpAffine(image, T, (row,col))
    cv2.imshow('Frame1', image)
    cv2.imshow('frame2', image2)
    k = cv2.waitKey(1)
    if k==ord('q'):
        break
    x=x+0.1
    y=y+0.1
cv2.destroyAllWindows()
    

#### 2. Rotation of Image

In [44]:
image = cv2.imread('C:\Lachin\Data Science\Data science\Opencv\img1.png')

In [45]:
row, col, chan = image.shape

In [49]:
R = cv2.getRotationMatrix2D((row/2,col/2), 45,0.5)

In [54]:
image2 = cv2.warpAffine(image, R, (row,col))

In [55]:
cv2.imshow('Frame1', image)
cv2.imshow('frame2', image2)
cv2.waitKey()#Time waiting for a keyboard argument
cv2.destroyAllWindows()

##### Animation

In [58]:
angle = 0

while(True):
    if angle == 360:
        angle = 0
    R = cv2.getRotationMatrix2D((row/2,col/2), angle,0.5)
    image2 = cv2.warpAffine(image, R, (row,col))
    cv2.imshow('Frame1', image)
    cv2.imshow('frame2', image2)
    k = cv2.waitKey(1)
    if k==ord('q'):
        break
    angle+=0.1
cv2.destroyAllWindows()

### Scaling of Images

##### Interpolation Method

In [17]:
image = cv2.imread('C:\Lachin\Data Science\Data science\Opencv\img1.png')
cv2.imshow('Image', image)
cv2.waitKey()
cv2.destroyAllWindows()

In [29]:
image2 = cv2.resize(image, dsize = (675,675), interpolation = cv2.INTER_AREA)
cv2.imshow('AREA', image2)
image2 = cv2.resize(image, dsize = None, fx=0.5 ,fy=0.5, interpolation = cv2.INTER_LINEAR)
cv2.imshow('LINEAR', image2)
image2 = cv2.resize(image, dsize = None, fx=0.5 ,fy=0.5, interpolation = cv2.INTER_CUBIC)
cv2.imshow('CUBIC', image2)
image2 = cv2.resize(image, dsize = None, fx=0.5 ,fy=0.5, interpolation = cv2.INTER_LANCZOS4)
cv2.imshow('LANCZOS', image2)
image2 = cv2.resize(image, dsize = None, fx=0.5 ,fy=0.5, interpolation = cv2.INTER_LINEAR_EXACT)
cv2.imshow('LINEAR_EXACT', image2)
image2 = cv2.resize(image, dsize = None, fx=0.5 ,fy=0.5, interpolation = cv2.INTER_NEAREST)
cv2.imshow('NEAREST', image2)
cv2.imshow('Image', image)
cv2.waitKey()
cv2.destroyAllWindows()
#For enlarging most of the time, LANCOS is giving perfect imag
#For downsizing area gives the best one


##### Pyramid Method

In [26]:
image2 = cv2.pyrDown(image)
image3 = cv2.pyrUp(image)
cv2.imshow('pyrdown', image2)
cv2.imshow('pyup', image3)
cv2.waitKey()
cv2.destroyAllWindows()

### Bluring and Smoothing

In [6]:
image1 = cv2.imread('C:\Lachin\Data Science\Data science\Opencv\img1.png')

In [7]:
kernel_5x5 = (np.ones((5,5), np.uint8))/25
kernel_9x9 = (np.ones((9,9), np.uint8))/25

In [8]:
image2 = cv2.filter2D(image1,-1, kernel_5x5)#Runs the filter matrix on the image matrix
image3 = cv2.filter2D(image1,-1, kernel_9x9)
cv2.imshow('Orgignal', image1)
cv2.imshow('Filter2d 5x5', image2)
cv2.imshow('filter 9x9', image3)
cv2.waitKey()
cv2.destroyAllWindows()

In [9]:
image4 = cv2.blur(image1,(5,5))
image5 = cv2.GaussianBlur(image1, (5,5), 0)
image6 = cv2.medianBlur(image1,5)
image7 = cv2.bilateralFilter(image1,9,75,75)#preserve edges and blur the image(more beneficial)
cv2.imshow('Orgignal', image1)
cv2.imshow('BLUR', image4)
cv2.imshow('GAUSSIAN BLUR', image5)
cv2.imshow('MEDIAN BLUR', image6)
cv2.imshow('BI LATERAL FILTER', image7)
cv2.waitKey()
cv2.destroyAllWindows()


### Image Sharpening

In [10]:
#Opposite of bluring
#this will sharpen the edges of the object
image1 = cv2.imread('C:\Lachin\Data Science\Data science\Opencv\img1.png')

In [19]:
kernal = np.array([[-1,-1,-1],[-1,9,-1],[-1,-1,-1]])
kernal1 = np.array([[-1,-1,-1,-1,-1],
                    [-1,-1,-1,-1,-1],
                    [-1,-1,25,-1,-1],
                    [-1,-1,-1,-1,-1],
                    [-1,-1,-1,-1,-1]])#Edges are more visible

In [20]:
image2 = cv2.filter2D(image1,-1, kernal1)

In [21]:
cv2.imshow('Orginal', image1)
cv2.imshow('Sharpened_Image', image2)#Edges are more visible
cv2.waitKey()
cv2.destroyAllWindows()

# Computer Vision Techniques

### Simple Thresholding(Global Thresholding)

In [22]:
#To identify the darker and the light areas of the picture
#Most of the time, best to work with the black and white images

In [3]:
image1 = cv2.imread('C:\Lachin\Data Science\Data science\Opencv\img1.png')
image1 = cv2.cvtColor(image1, cv2.COLOR_BGR2GRAY)
cv2.imshow('Orgignal', image1)
cv2.waitKey()
cv2.destroyAllWindows()

In [4]:
ret, image2 = cv2.threshold(image1, 140 , 225, cv2.THRESH_BINARY)
#Covert all pixels below 140(threshhold value) to 0
#convert all pixels above threshold to 255

In [5]:
ret, image3 = cv2.threshold(image1, 140, 225, cv2.THRESH_BINARY_INV)
#convert all pixels below 140 to 255
#covert all pixels above 140 to 0

In [10]:
ret, image4 = cv2.threshold(image1, 140, 225, cv2.THRESH_TRUNC)
#convert all above pixels which are above threshold to 140
#pixels below threshold value remain the same

In [7]:
ret, image5 = cv2.threshold(image1, 140, 225, cv2.THRESH_TOZERO)
#whatever above threshold value, remain the same
#pixels below threshold value, become 0

In [9]:
ret, image6 = cv2.threshold(image1, 140, 225, cv2.THRESH_TOZERO_INV)
#Pixels above threshold value, become 0
#pixels below threshold value remain the same

In [12]:
cv2.imshow('Orgignal', image1)
cv2.imshow('Binary', image2)
cv2.imshow('Binary_Inv', image3)
cv2.imshow('Trunc', image4)
cv2.imshow('Tozero', image5)
cv2.imshow('Tozero_Inv', image6)
cv2.waitKey()
cv2.destroyAllWindows()

### Adaptive Thresholding

In [13]:
image1 = cv2.imread('C:\Lachin\Data Science\Data science\Opencv\img2.jpg')
image1 = cv2.cvtColor(image1, cv2.COLOR_BGR2GRAY)

In [14]:
cv2.imshow('AT', image1)
cv2.waitKey()
cv2.destroyAllWindows()

In [18]:
image2 = cv2.adaptiveThreshold(image1, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 7, 5)
#blocksize must be odd and greater than 1

In [21]:
image3 = cv2.adaptiveThreshold(image1, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 7,5)

In [22]:
cv2.imshow('Original', image1)
cv2.imshow('Mean', image2)
cv2.imshow('Gaussian', image3)
cv2.waitKey()
cv2.destroyAllWindows()

### Erotion & Dialation

In [23]:
# Want good edges ----> Dialation
# Thinning out the edges -------> Erotion


In [24]:
image1 = cv2.imread('C:\Lachin\Data Science\Data science\Opencv\img3.png')

In [25]:
kernal = np.ones((5,5))

In [41]:
image2 = cv2.erode(image1,kernal, iterations=1)
image3 = cv2.dilate(image1, kernal, iterations=1)

In [42]:
cv2.imshow('Orgignal', image1)
cv2.imshow('Erotion', image2)
cv2.imshow('Dialation', image3)
cv2.waitKey()
cv2.destroyAllWindows()

In [35]:
image4 = cv2.morphologyEx(image1, cv2.MORPH_OPEN, kernal)
image5 = cv2.morphologyEx(image1, cv2.MORPH_CLOSE, kernal)
# Opening ----> first do the erotion and then dialation
# Closing ----> first do the dialtion and then erotion

In [36]:
cv2.imshow('Orgignal', image1)
cv2.imshow('Open', image4)
cv2.imshow('Close', image5)
cv2.waitKey()
cv2.destroyAllWindows()

### Edge Detection (Canny)

In [43]:
image1 = cv2.imread('C:\Lachin\Data Science\Data science\Opencv\img1.png')

In [58]:
image2 = cv2.Canny(image1, 30,100)
#when threshold 2 is increasing, edges will be missed
#When it is decreasing, edges will be identified better(,ore edges)

In [59]:
cv2.imshow('Original', image1)
cv2.imshow('Edge_Detection', image2)
cv2.waitKey()
cv2.destroyAllWindows()

### Image Pyramids

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import cv2 as cv2

In [5]:
image1 = cv2.imread('C:\Lachin\Data Science\Data science\Opencv\img1.png')
# image2 = cv2.pyrDown(image1)
# image3 = cv2.pyrUp(image1)
# cv2.imshow('Original', image1)
# cv2.imshow('Down', image2)
# cv2.imshow('Up', image3)
# cv2.waitKey()
# cv2.destroyAllWindows()

In [2]:
def gaussian(image):
    gp = []
    gp.append(image)
    for i in range(6):
        image = cv2.pyrDown(image)
        gp.append(image)
        cv2.imshow(str(i), gp[i])
    

In [6]:
def laplacian(image):
    gp = [image]
    for i in range(6):
        image = cv2.pyrDown(image)
        gp.append(image)
    lp = [gp[5]]
    for i in range(5,0,-1):
        gauss_expand = cv2.pyrUp(gp[i])
        lap = cv2.subtract(gp[i-1], gauss_expand)
        lp.append(lap)
    return lp
        

In [13]:
gaussian(image1)
cv2.waitKey()
cv2.destroyAllWindows()

### Contours

In [23]:
original_image = cv2.imread('C:\Lachin\Data Science\Data science\Opencv\opencv2.png')
image = cv2.cvtColor(original_image, cv2.COLOR_BGR2GRAY)

In [35]:
RET, image1 = cv2.threshold(image,170,225,0)
image1 = cv2.Canny(image,30,50)# Canny is detetciong most of the edges here, withoout it number of contours will be reduced

In [40]:
contours, hierarchy = cv2.findContours(image1, cv2.RETR_LIST, cv2.CHAIN_APPROX_NONE)
#CHAIN_APPROX_SIMPLE is better for shapes,it doesn't give all the values
cv2.drawContours(original_image, contours, -1, (25,255,156), 3)
#-1 for all the contours, otherwise the index of the list

array([[[ 25, 255, 156],
        [ 25, 255, 156],
        [ 25, 255, 156],
        ...,
        [ 25, 255, 156],
        [ 25, 255, 156],
        [ 25, 255, 156]],

       [[ 25, 255, 156],
        [ 25, 255, 156],
        [ 25, 255, 156],
        ...,
        [ 25, 255, 156],
        [ 25, 255, 156],
        [ 25, 255, 156]],

       [[ 25, 255, 156],
        [ 25, 255, 156],
        [ 25, 255, 156],
        ...,
        [ 25, 255, 156],
        [ 25, 255, 156],
        [ 25, 255, 156]],

       ...,

       [[ 25, 255, 156],
        [ 25, 255, 156],
        [ 25, 255, 156],
        ...,
        [ 25, 255, 156],
        [ 25, 255, 156],
        [ 25, 255, 156]],

       [[ 25, 255, 156],
        [ 25, 255, 156],
        [ 25, 255, 156],
        ...,
        [ 25, 255, 156],
        [ 25, 255, 156],
        [ 25, 255, 156]],

       [[ 25, 255, 156],
        [ 25, 255, 156],
        [ 25, 255, 156],
        ...,
        [ 25, 255, 156],
        [ 25, 255, 156],
        [ 25, 255, 156]]

In [41]:
cv2.imshow('Original_Image', original_image)
cv2.waitKey()
cv2.destroyAllWindows()

##### Detetcting only the Red contour

In [42]:
original_image = cv2.imread('C:\Lachin\Data Science\Data science\Opencv\opencv2.png')
image = cv2.cvtColor(original_image, cv2.COLOR_BGR2HSV)

In [44]:
lr = np.array((0,70,70))
ur = np.array((10,255,255))
mask1 = cv2.inRange(image,lr, ur)

In [45]:
lr = np.array((170,70,70))
ur = np.array((180,255,255))
mask2 = cv2.inRange(image,lr,ur)

In [46]:
mask = mask1 + mask2

In [47]:
contours, hierarchy = cv2.findContours(mask, cv2.RETR_LIST, cv2.CHAIN_APPROX_NONE)
#CHAIN_APPROX_SIMPLE is better for shapes,it doesn't give all the values
cv2.drawContours(original_image, contours, -1, (25,255,156), 3)
#-1 for all the contours, otherwise the index of the list

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [48]:
cv2.imshow('Original_Image', original_image)
cv2.waitKey()
cv2.destroyAllWindows()

##### Sorting contours

In [54]:
kernal = np.ones((512,512,3), np.uint8)
kernal=kernal*255

In [55]:
cv2.rectangle(kernal, (50,50),(150,150),(0,0,0),-1)
cv2.circle(kernal, (100,250),90,(0,0,0),-1)
cv2.ellipse(kernal,(350,300),(150,200),0,0,360,(0,0,0),-1)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [56]:
cv2.imshow('shapes', kernal)
cv2.waitKey()
cv2.destroyAllWindows()

In [57]:
cv2.imwrite('C:\Lachin\Data Science\Data science\Opencv\shapes.png', kernal)

True

In [58]:
###Sorting Starts now

In [3]:
original_image = cv2.imread('C:\Lachin\Data Science\Data science\Opencv\shapes.png')
cv2.imshow('Shapes', original_image)
cv2.destroyAllWindows()

In [4]:
image = cv2.cvtColor(original_image, cv2.COLOR_BGR2GRAY)

In [5]:
ret, image = cv2.threshold(image,70,255,0)

In [6]:
contours, hierarchy = cv2.findContours(image, cv2.RETR_LIST, cv2.CHAIN_APPROX_NONE)

In [7]:
sorted_contours = sorted(contours, key=cv2.contourArea, reverse=True)[1:]
#Because the 0th index contour is the whole white background image contour
#IF reverse False, indexing must be [:-1]

In [10]:
for i, cnt in enumerate(sorted_contours):
    m = cv2.moments(cnt)
    if m["m00"] !=0:
        cx = int(m["m10"]/m["m00"])
        cy = int(m["m01"]/m["m00"])
    else:
        cx=0
        cy=0
    
    cv2.drawContours(original_image, [cnt], -1, (200,100,0),3)
    cv2.putText(original_image, str(i+1), (cx,cy), cv2.FONT_HERSHEY_COMPLEX, 1 ,(255,200,0),1)
    cv2.imshow('Original', original_image)
    cv2.waitKey()
cv2.waitKey()
cv2.destroyAllWindows()

##### Matching contours

In [27]:
kernal2 = np.ones((512,512,3), np.uint8)
kernal2=kernal2*255
cv2.circle(kernal2, (256,256),100,(0,0,0),-1)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [31]:
# cv2.imshow('circle', kernal)
# cv2.waitKey()
# cv2.destroyAllWindows()

In [29]:
cv2.imwrite('C:\\Lachin\\Data Science\\Data science\\Opencv\\template1.jpg', kernal2)

True

In [33]:
#Start of matching part

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import cv2 as cv2

In [30]:
original_image = cv2.imread('C:\\Lachin\\Data Science\\Data science\\Opencv\\shapes.png')
template = cv2.imread('C:\\Lachin\\Data Science\\Data science\\Opencv\\template1.jpg')
cv2.imshow('Original', original_image)
cv2.imshow('template', template)
cv2.waitKey()
cv2.destroyAllWindows()

In [31]:
image = cv2.cvtColor(original_image, cv2.COLOR_BGR2GRAY)
image1 = cv2.cvtColor(template, cv2.COLOR_BGR2GRAY)

In [32]:
RET, image = cv2.threshold(image,170,225,0)
RET, image1 = cv2.threshold(image,170,225,0)

In [33]:
contours, hierarchy = cv2.findContours(image1, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
sorted_contours = sorted(contours, key=cv2.contourArea, reverse=True)

In [34]:
template_contours = sorted_contours[1]

In [35]:
contours, hierarchy = cv2.findContours(image, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
sorted_contours = sorted(contours, key=cv2.contourArea, reverse=True)[1:]

In [36]:
smatch=10
for c in sorted_contours:
    match = cv2.matchShapes(template_contours,c,1,0.0)
    print(match)
    if match < smatch:
        cnt=c
        smatch = match

0.0
0.02789337885795029
0.004204643287673893


In [37]:
cv2.drawContours(original_image, cnt, -1, (200,100,0),3)
cv2.imshow('Original', original_image)
cv2.imshow('template', template)
cv2.waitKey()
cv2.destroyAllWindows()
